### ISSUE TITLE
Script finds few Ignite 2021H1 slides. Is this by design? 

### ISSUE THREAD

**Issue by jaimerodriguez** [michelderooij/Get-EventSession#21]
hi folks, the script looks great, but when i run it, i can't get most slides from March 2021. Is this by design (e.g.,  Microsoft removed them vs. script guessing wrong path)? or could there be an issue with the script? 

If you happen to have tested/downloaded the March 2021 slides before, i am looking for slides for Session:  
STUDIO23 - Microsoft Cloud for Financial Services Overview- Accelerate Innovation for Sustainable Growth (No Timestamp)
WARNING: Skipping: Slidedeck unavailable https://medius.studios.ms/video/asset/PPT/IG21-STUDIO23 

Any chance you can share it directly (if you downloaded it before)?   
Thanks in advance!

**Comment by michelderooij** [comment]
1) After a while, Microsoft moves the content (nowadays usually YouTube) and it will no longer be available on the original location, nor always available on the location referred to in the session data returned. That's why there is some guessing involved then there are no direct links published.
2) Slidedecks are not always published.
3) Not all events are recorded and published - I don't have Studio23 content.
